### ISSUE TITLE
Remove corsProxy or factor out as an option

### ISSUE THREAD

**Issue by maxsatula** [TooTallNate/iheart#2]
https://cors.now.sh/ seems to be dead

I removed any references to `corsProxy` variable to make this module work.

Either remove it or make it a configurable option, in case if anyone still needs a proxy.

Thanks

**Comment by TooTallNate** [comment]
👍 Pull request welcome for a `proxy` option. Note though that we need a default proxy _when in the browser only_, since CORS headers are not present in the browser. In Node.js this isn't a problem, but for the sake of code simplicity I didn't fork the logic originally.

**Comment by maxsatula** [comment]
I do not want to produce bad code. Not sure how to do it better.
First option may look better, but will break existing code whoever uses the module (they will need to add extra parenthesis to `require`:
```js
const iheart = require('iheart')(); // default proxy
const iheart = require('iheart')({ proxy: "http://blah-blah.com" }); // use specific non-default
const iheart = require('iheart')({ proxy: null }); // no proxy
```
Option number two:
```js
const iheart = require('iheart'); // good old syntax here
iheart.setOptions({ proxy: "http://blah-blah.com" });
```
Or maybe option number 3 (no idea what).

**Comment by TooTallNate** [comment]
IMO we should add an Options parameter to each of the API functions and have `proxy` be the only option supported for now.

**Comment by TooTallNate** [comment]
So `iheart.search('107.7', { proxy: 'foo' })`

**Comment by maxsatula** [comment]
Looks equally bad. User will have to carry that option everywhere.

**Comment by TooTallNate** [comment]
Indeed, but you have to do the same thing with i.e. `agent` for http.Client requests in Node.js, so I think it's the most aligned with the Node API that way.

**Comment by TooTallNate** [comment]
Not totally relevant to the issue at hand, but https://cors.now.sh is back up
