### ISSUE TITLE
Get radio station description by id

### ISSUE THREAD

**Issue by maxsatula** [TooTallNate/iheart#5]
I can offer to create a function `getById(_station)` which returns a whole JSON of radio station taking numeric station id as an argument. It is almost identical to `streamURL(_station)`, but it stops before streams are extracted and returns `body.hits[0]` instead.

It can be useful, for example, if one stores station ids in a favourites list, and needs to resolve a station name, its description, logo etc. In this case there will be no need to store entire station JSON object in the favourites. Also, cached station information can be outdated otherwise.

**Caveat**

Apparently, `https://api.iheart.com/api/v1/catalog/searchAll` and `https://api.iheart.com/api/v2/content/liveStations/` and thus `iheart.search(...)` and `iheart.streamURL(...)` respectively return a little bit different JSON objects. For instance, `newlogo` property exits in one but does not in another.  `logo` property, in its turn, contains `{img_url_1}` string in the former case, which makes logo URL unusable unless substitution value is found and replaced.

**Comment by TooTallNate** [comment]
Great idea!
👍 Pull request welcome
